site/frontend/controllers/AktionController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Aktion;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use sanex\simplefilter\SimpleFilter;
use frontend\models\ContactForm;

/**
 * AktionController implements the CRUD actions for Aktion model.
 */
class AktionController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Aktion models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Aktion::find(),
        ]);

        $aktion = Aktion::find()->where(['not',['imginfobox'=> null]])->orderBy('enddate ASC')->one();

        $model = new Aktion;

        $query = new \yii\db\ActiveQuery($model);
        $query->orderBy('id'); 

        $ajaxViewFile = '@app/views/aktion/index-ajax';

        $filter = SimpleFilter::getInstance();
        $filter->setParams([
            'model' => $model,
            'query' => $query,
            'useAjax' => true,
            // 'useCache' => true,
            'useDataProvider' => true,
        ]);

        return $this->render('index', [
            'filter' => $filter,
            'ajaxViewFile' => $ajaxViewFile,
            'aktion' => $aktion,
            // 'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Aktion model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $call = new ContactForm();
        $testdrive = new ContactForm();

        if ($call->load(Yii::$app->request->post()) && $call->validate()) {
            if ($call->sendEmail(Yii::$app->params['adminEmail'])) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        if ($testdrive->load(Yii::$app->request->post()) && $testdrive->validate()) {
            if ($testdrive->sendTestdrive(Yii::$app->params['adminEmail'])) {
                return $this->redirect(['view', 'id' => $model->id]);
            } 
        }

        return $this->render('view', [
            'model' => $model,
            'testdrive' => $testdrive,
            'call' => $call,
        ]);
    }

    /**
     * Finds the Aktion model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Aktion the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Aktion::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

site/frontend/controllers/CategoryController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Category;
use common\models\Aktion;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CategoryController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Category models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Category::find(),
        ]);

        $aktions = Aktion::find()->where(['not',['imginfobox'=> '']])->orderBy('enddate ASC')->all();
        // $aktions = Aktion::find()->where(['and', 'type=0',['not',['imginfobox'=> '']]])->orderBy('enddate ASC')->all();

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'aktions' => $aktions,
        ]);
    }

    /**
     * Displays a single Category model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Finds the Category model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Category::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

site/frontend/views/category/_items.php
<?php 
use common\models\Carcass;
use yii\helpers\Html;
?>
<div class="models__item">
    <div class="container-content container-content_padding-all">
        <div class="title" id="anchor-<?= $model->id ?>"><?= $model->title ?></div>
        <div class="models-list">
            <?php foreach (Carcass::find()->where(['categoryId'=>$model->id])->all() as $key => $carcass): ?>
                <div class="models-list__item figure uk-overlay uk-overlay-hover">
                    <?= Html::a(Html::img('@web/images/img-model.jpg',['alt'=>'','width'=>'233px','height'=>'321px']).
                        '<figcaption class="uk-overlay-panel uk-overlay-background uk-overlay-ignore uk-flex uk-flex-bottom uk-flex-middle uk-text-center">
                            <div>
                                <h3 class="models-list__title">'.$carcass->title.'</h3>
                                <div class="models-list__cont">'.$carcass->description.'</div>
                            </div>
                        </figcaption>', 
                        ['carcass/view','id'=>$carcass->id], ['target' => '_blank']) ?>
                </div>
            <?php endforeach ?>
        </div>
    </div>
</div>

site/frontend/views/category/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Модельный ряд';
?>
<div class="mainWrapper mainWrapper_bg mainWrapper_height-auto" style="background-image: url(&quot;/images/slide.jpg&quot;)">
    <?= $this->render('//layouts/header_nav') ?>
    <div class="page-title">
        <div class="container-content">
            <ul class="breadcrumbs">
                <li class="breadcrumbs__item"><a href="/" target="">Главная</a></li> -
                <li class="breadcrumbs__item"><span>Модельный ряд</span></li>
            </ul>
            <h1 class="page-title__h1">Модельный ряд</h1>
        </div>
    </div>
    <div class="container-content">
        <div class="actions-infobox">
            <div class="actions-infobox-slider">
                <div id="actions-infobox-slider">
                    <?php if ($aktions != NULL): ?>
                        <?php foreach ($aktions as $key => $aktion): ?>
                            <div class="actions-infobox__cont">
                                <div class="uk-grid uk-grid-medium">
                                    <div class="uk-width-large-4-10 uk-text-center">
                                        <div class="countdown" data-enddate="<?= date('Y, m, d',$aktion->enddate) ?>"></div>
                                        <h2 class="actions-infobox__title"><?= $aktion->title ?></h2>
                                        <p class="actions-infobox__anons"><?php $text = substr($aktion->description,0,200); echo $text."..."; ?></p>
                                        <?= Html::a('Подробнее', ['aktion/view','id'=>$aktion->id], ['class' => 'btn btn_ghost uk-button','target'=>'_blank']) ?>
                                    </div>
                                    <div class="uk-width-large-6-10">
                                        <?= Html::img('@web/images/'.$aktion->imginfobox,['alt'=>$aktion->title]) ?>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach ?>
                    <?php endif ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?= ListView::widget([
  'dataProvider' => $dataProvider,
  'itemView' => '_items',
  'options'=>['class' => 'models'],
  'layout' => "{items}",
]) ?>

site/frontend/views/category/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Category */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="category-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'image',
            'costfrom',
        ],
    ]) ?>

</div>