site/frontend/controllers/CarController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Car;
use common\models\Slide;
use common\models\Aktion;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use frontend\models\ContactForm;


/**
 * CarController implements the CRUD actions for Car model.
 */
class CarController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Car models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Car::find(),
        ]);

        $aktion = Aktion::find()->where(['not',['imginfobox'=> null]])->orderBy('enddate ASC')->one();

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'aktion' => $aktion,
        ]);
    }

    /**
     * Displays a single Car model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $images = Slide::findAll(['carId' => $model->id]);
        $call = new ContactForm();

 /*        if ($call->load(Yii::$app->request->post()) && $call->validate()) {
            $call = new ContactForm();
            if ($call->sendEmail(Yii::$app->params['adminEmail'])) {
                return $this->redirect(['index']);
            }
        }*/

        return $this->renderAjax('view', [
            'model' => $model,
            'images' => $images,
            // 'call' => $call,
        ]);
    }

    /**
     * Finds the Car model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Car the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Car::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

site/frontend/controllers/CategoryController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Category;
use common\models\Aktion;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CategoryController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Category models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Category::find(),
        ]);

        $aktions = Aktion::find()->where(['not',['imginfobox'=> '']])->orderBy('enddate ASC')->all();
        // $aktions = Aktion::find()->where(['and', 'type=0',['not',['imginfobox'=> '']]])->orderBy('enddate ASC')->all();

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'aktions' => $aktions,
        ]);
    }

    /**
     * Displays a single Category model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Finds the Category model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Category::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

site/frontend/controllers/PageController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Page;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use frontend\models\ContactForm;

/**
 * PageController implements the CRUD actions for Page model.
 */
class PageController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }


    /**
     * Creates a new Page model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCredit()
    {
        $model = $this->findModel(1);
        $call = new ContactForm();

        if ($call->load(Yii::$app->request->post()) && $call->validate()) {
            if ($call->sendEmail(Yii::$app->params['adminEmail'])) {
                return $this->redirect(['credit']);
            }
        }

        return $this->render('credit', [
                'model' => $model,
                'call' => $call,
            ]);
    }

    public function actionService()
    {
        $model = $this->findModel(2);
        $testdrive = new ContactForm();

        if ($testdrive->load(Yii::$app->request->post()) && $testdrive->validate()) {
            if ($testdrive->sendTestdrive(Yii::$app->params['adminEmail'])) {
                return $this->redirect(['service']);
            } 
        }

        return $this->render('service', [
            'model' => $model,
            'testdrive' => $testdrive,
        ]);
    }
   
    public function actionContacts()
    {
        $model = $this->findModel(3);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect('index');
        } else {
            return $this->render('contacts', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Finds the Page model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Page the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Page::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

site/frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use common\models\LoginForm;
use common\models\Category;
use common\models\Page;
use common\models\Car;
use common\models\Slide;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\data\ActiveDataProvider;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {   
        return $this->render('index', [
            'categories' => Category::find()->all(),
            'homePage' => Page::findOne(4),
            'slides' => Slide::findAll(['pageId'=>4]),
        ]);
    }

    public function actionCall()
    {
        $call = new ContactForm();
        if ($call->load(Yii::$app->request->post()) && $call->validate()) {
            if ($call->sendEmail(Yii::$app->params['adminEmail'])) {
                return $this->redirect('/');
            }
            
        }
    }

    public function actionTestdrive()
    {
        $testdrive = new ContactForm();
        if ($testdrive->load(Yii::$app->request->post()) && $testdrive->validate()) {
            if ($testdrive->sendTestdrive(Yii::$app->params['adminEmail'])) {
                return $this->redirect('/');
            }
            
        }
    }

/*    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }*/

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

site/frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

site/frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Обратная связь';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        Если вы хотите отправить нам сообщение, заполните поля формы и отправьте нам.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

site/frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

site/frontend/views/site/index.php
<?php
use backend\assets\AppAsset;
use common\models\Carcass;
use yii\helpers\Html;
use yii\widgets\Menu;
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;
use yii\widgets\ListView;
use yii\bootstrap\Button;
use common\models\Page;

$data = Page::findOne(4);
/* @var $this yii\web\View */

$this->title = 'Акции';
?>
<div class="hm-first-screen mainWrapper uk-flex">
    <div class="hm-first-screen__cont uk-flex uk-flex-column uk-flex-space-between">
        <header class="header header_hm">
            <div class="container-content">
                <div class="uk-flex uk-flex-space-between uk-flex-wrap uk-flex-middle">
                    <div class="header__left">
                        <div class="header__logo">
                            <?= Html::a(Html::img('@web/images/logo.png',['width'=>'40px']),['/']) ?>
                        </div>
                        <?= Html::tag('button', 'Бесплатный звонок', ['class' => 'uk-button','data-uk-modal' => '{target:\'#modal-call\'}']) ?>
                        <?= Html::a('<i class="icon sprite-i-phone-vol"></i> '.$data->c13,'tel:'.$data->c13) ?>
                        <?= Html::a('<i class="icon sprite-i-phone-mobile"></i> '.$data->c21,'tel:'.$data->c21) ?>
                    </div>
                    <div class="header__center">
                        <div class="header__logo">
                            <a href="/"><img src="/images/logo.png"></a>
                        </div>
                    </div>
                    <div class="header__right">
                        <span class="header__adres"><?= $data->c22 ?></span>
                        <a href="#modal-map" data-uk-modal title="title"><i class="uk-icon-map-marker"></i> Как проехать?</a>
                        <?= Html::tag('button', 'Запись на тест-драйв', ['class' => 'uk-button','data-uk-modal' => '{target:\'#modal-testdrive\'}']) ?>
                        <a class="sidebar-tgl" href="#sidebar" data-uk-offcanvas>Меню <i class="uk-icon-bars"></i></a></div>
                </div>
            </div>
        </header>
        <div class="hm-slider-wrap">
            <ul class="hm-slider-wrap__bg" id="hm-slider">
                <?php foreach ($slides as $key => $item): ?>
                    <li style="background-image: url(<?= Url::to('@web/images/').$item->image ?>)"></li>
                <?php endforeach ?>
            </ul>
            <div class="hm-slider">
                <div class="container-content">
                    <ul class="hm-slider__caption" id="hm-slider-caption">
                        <?php foreach ($slides as $key => $item): ?>
                            <li class="uk-text-center">
                                <?= Html::img('@web/images/'.$item->slidelogo) ?>
                                <h3 class="hm-slider__title"><?= $item->title ?></h3>
                                <div class="hm-slider__caption"><?= $item->caption ?></div>
                            </li>
                        <?php endforeach ?>
                    </ul>
                    <div class="hm-slider__pager" id="bx-pager">
                        <?php foreach ($slides as $key => $item): ?>
                            <?= Html::a('', ['#'],['class'=>'hm-slider__dotnav','data-slide-index'=>$key]) ?>
                        <?php endforeach ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="hm-first-screen__bottom">
            <div class="advantages">
                <div class="container-content">
                    <div class="advantages__grid uk-flex uk-flex-wrap uk-flex-center">
                        <div class="advantages__item-wrap">
                            <div class="advantages__item">
                                <div class="advantages__ico"><?= Html::img('@web/images/1.png') ?></div>
                                <div class="advantages__name">Выгода по трейд-ин</div>
                            </div>
                        </div>
                        <div class="advantages__item-wrap">
                            <div class="advantages__item">
                                <div class="advantages__ico"><?= Html::img('@web/images/2.png') ?></div>
                                <div class="advantages__name">Утилизация 2016</div>
                            </div>
                        </div>
                        <div class="advantages__item-wrap">
                            <div class="advantages__item">
                                <div class="advantages__ico"><?= Html::img('@web/images/3.png') ?></div>
                                <div class="advantages__name">Автомобили в наличии и с ПТС</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-content">
                <div class="hm-first-screen__menu">
                    <?php echo Menu::widget([
                        'items' => [
                            ['label' => 'Акции', 'url' => ['/aktion/index'],'template' => '<a href="{url}" class="menu-main__link">{label}</a>','options' => ['class' => 'menu-main__item']],
                            ['label' => 'Модельный ряд', 'url' => ['/category/index'],'template' => '<a href="{url}" class="menu-main__link">{label}</a>','options' => ['class' => 'menu-main__item']],
                            ['label' => 'Кредит', 'url' => ['/page/credit'],'template' => '<a href="{url}" class="menu-main__link">{label}</a>','options' => ['class' => 'menu-main__item']],
                            ['label' => 'Сервис', 'url' => ['/page/service'],'template' => '<a href="{url}" class="menu-main__link">{label}</a>','options' => ['class' => 'menu-main__item']],
                            ['label' => 'Трейд-ин', 'url' => ['/car/index'],'template' => '<a href="{url}" class="menu-main__link">{label}</a>','options' => ['class' => 'menu-main__item']],
                            ['label' => 'Контакты', 'url' => ['/page/contacts'],'template' => '<a href="{url}" class="menu-main__link">{label}</a>','options' => ['class' => 'menu-main__item']],
                        ],
                        'activeCssClass'=>'active',
                        'options' => [
                            'class' => 'menu-main',
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="hm-auto mainWrapper uk-flex">
    <div class="hm-auto__wrap uk-flex uk-flex-wrap">
        <?php foreach ($categories as $key => $model): ?>
            <div class="hm-auto-item uk-flex uk-flex-bottom" style="background-image:url(<?= Url::to('@web/images/').$model->image ?>)">
                <div class="hm-auto-item__cont">
                    <div class="hm-auto-item__name"><?= $model->title ?></div>
                    <div class="hm-auto-item__price">от <?= $model->costfrom ?> Р.</div>
                    <div class="hm-auto-item__car-body">
                        <ul class="hm-auto-item__car-body-list">
                            <?php foreach (Carcass::find()->where(['categoryId'=>$model->id])->all() as $key => $carcass): ?>
                                <li><?= Html::a($carcass->title, ['category/index','#'=>'anchor-'.$carcass->categoryId],['title'=>$carcass->title]) ?></li>
                            <?php endforeach ?>
                        </ul>
                    </div>
                </div>
            </div>
        <?php endforeach ?>
    </div>
</div>
<div class="hm-about">
    <div class="container-content container-content_padding-all">
        <div class="grid">
            <div class="col-l-4 col-m-12 uk-margin-bottom">
                <div class="hm-about__title"><?= $homePage->c11 ?></div> 
            </div>
            <div class="col-l-8 col-m-12">
                <div class="content">
                    <?= $homePage->block1 ?>
                </div>
            </div>
        </div>
    </div>
</div>

site/frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Вход на сайт';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Введите ваш логин и пароль, который вы указали при регистрации:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    Если вы забыли пароль, то вы можете воспользоваться сбросом пароля <?= Html::a('Сброс пароля', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

site/frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Запрос о сбросе пароля';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Введите ваш email, указанный при регистрации, на данный email будет выслана ссылка для смены пароля.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Отправить запрос', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

site/frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Сброс пароля';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Укажите новый пароль:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Сменить пароль', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

site/frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Для регистрации заполните все нижеперечисленные поля:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Зарегистрироваться', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>